package guessmarket.engine;

public enum EngineErrorCode {
    INVALID_XML_PATH,
    XML_FILE_NOT_FOUND,
    XML_FILE_ACCESS_FAILED,
    XML_STRUCTURE_INVALID,
    XML_DATA_INVALID,
    ENGINE_CONFIGURATION_ERROR,
    NO_SYSTEM_LOADED,
    EVENT_NOT_FOUND,
    EVENT_NOT_OPEN,
    INVALID_OPTION,
    INVALID_QUANTITY,
    FINANCIAL_CALCULATION_FAILED,
    INVALID_STATE_PATH,
    STATE_FILE_NOT_FOUND,
    STATE_FILE_ACCESS_FAILED,
    SAVED_STATE_INVALID
}
